// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9yeO9k-yqf61OmE67MG3oRRpvbm3cIQ',
    appId: '1:535637157454:web:33eda5951a008c5de5051f',
    messagingSenderId: '535637157454',
    projectId: 'project-theta-a1044',
    authDomain: 'project-theta-a1044.firebaseapp.com',
    databaseURL: 'https://project-theta-a1044-default-rtdb.firebaseio.com',
    storageBucket: 'project-theta-a1044.firebasestorage.app',
    measurementId: 'G-CKZ4PCE95L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBDy0x7XZayvRwO-SKoUZf8Dcdes3GOkM',
    appId: '1:535637157454:android:7226e39a75602ec2e5051f',
    messagingSenderId: '535637157454',
    projectId: 'project-theta-a1044',
    databaseURL: 'https://project-theta-a1044-default-rtdb.firebaseio.com',
    storageBucket: 'project-theta-a1044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvllHcLRKvNx3Hh0702IehuLrXcUUJZo',
    appId: '1:535637157454:ios:461b6a8a37baa7d6e5051f',
    messagingSenderId: '535637157454',
    projectId: 'project-theta-a1044',
    databaseURL: 'https://project-theta-a1044-default-rtdb.firebaseio.com',
    storageBucket: 'project-theta-a1044.firebasestorage.app',
    androidClientId: '535637157454-pdie3h2ove6qqj6ihbohonohhd5r9hrf.apps.googleusercontent.com',
    iosClientId: '535637157454-llbllkjaee0ekt14sokuqbchnctvdq5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mjifarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvllHcLRKvNx3Hh0702IehuLrXcUUJZo',
    appId: '1:535637157454:ios:461b6a8a37baa7d6e5051f',
    messagingSenderId: '535637157454',
    projectId: 'project-theta-a1044',
    databaseURL: 'https://project-theta-a1044-default-rtdb.firebaseio.com',
    storageBucket: 'project-theta-a1044.firebasestorage.app',
    androidClientId: '535637157454-pdie3h2ove6qqj6ihbohonohhd5r9hrf.apps.googleusercontent.com',
    iosClientId: '535637157454-llbllkjaee0ekt14sokuqbchnctvdq5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mjifarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9yeO9k-yqf61OmE67MG3oRRpvbm3cIQ',
    appId: '1:535637157454:web:f29b62bc04e96cd3e5051f',
    messagingSenderId: '535637157454',
    projectId: 'project-theta-a1044',
    authDomain: 'project-theta-a1044.firebaseapp.com',
    databaseURL: 'https://project-theta-a1044-default-rtdb.firebaseio.com',
    storageBucket: 'project-theta-a1044.firebasestorage.app',
    measurementId: 'G-EX5M7D8WR4',
  );
}
