import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart'; // Needed for SnackBar
import 'package:geolocator/geolocator.dart'; // REQUIRED: Import geolocator for location
// Removed: import 'package:firebase_database/firebase_database.dart'; // NO LONGER NEEDED HERE

// Function to get current user location (Requires geolocator permissions setup)
Future<Position?> getCurrentUserLocation() async {
  bool serviceEnabled;
  LocationPermission permission;

  serviceEnabled = await Geolocator.isLocationServiceEnabled();
  if (!serviceEnabled) {
    print('Location services are disabled.');
    // Consider showing a dialog to the user
    return null;
  }

  permission = await Geolocator.checkPermission();
  if (permission == LocationPermission.denied) {
    permission = await Geolocator.requestPermission();
    if (permission == LocationPermission.denied) {
      print('Location permissions are denied');
      // Consider showing a dialog explaining why permission is needed
      return null;
    }
  }

  if (permission == LocationPermission.deniedForever) {
    print('Location permissions are permanently denied, we cannot request permissions.');
    // Consider showing a dialog directing user to app settings
    return null;
  }

  try {
    return await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high);
  } catch (e) {
    print('Error getting location: $e');
    return null;
  }
}

// Corrected function to call Vercel and return the diagnosis details
// along with the Firebase ID and cropLogId generated by your Vercel function.
Future<Map<String, dynamic>?> callPlantDiagnosisVercel(
    String base64Image,
    String cropLogId, // This cropLogId is passed to Vercel, and now returned
    String plantId,
    BuildContext context,
    {double? latitude, double? longitude}
) async {
  try {
    // Get Firebase User ID Token
    String? idToken = await FirebaseAuth.instance.currentUser?.getIdToken();

    if (idToken == null) {
      print("User not authenticated. Cannot call Vercel function.");
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Authentication required. Please log in.')),
      );
      return null;
    }

    // Prepare the request body map
    Map<String, dynamic> requestBody = {
      'base64Image': base64Image,
      'cropLogId': cropLogId,
      'plantId': plantId,
    };

    // Conditionally add latitude and longitude if they are provided
    if (latitude != null) {
      requestBody['latitude'] = latitude;
    }
    if (longitude != null) {
      requestBody['longitude'] = longitude;
    }

    final response = await http.post(
      Uri.parse('https://mjifarms-backend.vercel.app/diagnose'), // Your Vercel endpoint
      headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8',
        'Authorization': 'Bearer $idToken',
      },
      body: jsonEncode(requestBody),
    );

    if (response.statusCode == 200) {
      final Map<String, dynamic> responseData = jsonDecode(response.body);
      print("Vercel Function Result: $responseData");

      if (responseData['status'] == 'success') {
        // Extract diagnosis details, diagnosis ID, and cropLogId from the Vercel response
        final Map<String, dynamic>? diagnosisDetails = responseData['diagnosisDetails'];
        final String? diagnosisId = responseData['diagnosisId']; // Firebase ID from Vercel
        final String? returnedCropLogId = responseData['cropLogId']; // <-- NEW: Get cropLogId from Vercel

        if (diagnosisDetails != null && diagnosisId != null && returnedCropLogId != null) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Plant diagnosed and saved successfully!')),
          );

          // Return a single map containing all necessary info, including the diagnosisId and cropLogId
          return {
            'pestOrDisease': diagnosisDetails['pestOrDisease'] ?? 'Unknown Issue',
            'confidenceLevel': (diagnosisDetails['confidenceLevel'] as num?)?.toDouble() ?? 0.0,
            'recommendations': List<String>.from(diagnosisDetails['recommendations'] ?? []),
            'relatedDiseaseImages': List<String>.from(diagnosisDetails['relatedDiseaseImages'] ?? []),
            'diagnosisId': diagnosisId,
            'cropLogId': returnedCropLogId, // <-- NEW: Pass cropLogId back to MyDiagnosisScreen
          };
        } else {
          print("Vercel response missing 'diagnosisDetails', 'diagnosisId', or 'cropLogId'.");
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Diagnosis details incomplete from server.')),
          );
          return null;
        }
      } else {
        print("Diagnosis failed from Vercel: ${responseData['message']}");
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Diagnosis failed: ${responseData['message']}')),
        );
        return null;
      }
    } else if (response.statusCode == 405) {
      print("Vercel Function Error: 405 Method Not Allowed.");
      print("Response body: ${response.body}");
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Server Error: Method Not Allowed. Please check backend configuration.')),
      );
      return null;
    } else if (response.statusCode == 400) {
        print("Vercel Function Error: 400 Bad Request. ${response.body}");
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Invalid request: ${jsonDecode(response.body)['message'] ?? response.body}')),
        );
        return null;
    }
    else {
      print("Vercel Function Error: ${response.statusCode}");
      print("Response body: ${response.body}");
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('An unexpected server error occurred (${response.statusCode}).')),
      );
      return null;
    }
  } catch (e) {
    print('Error calling Vercel function: $e');
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Network error: Failed to connect to server. ($e)')),
    );
    return null;
  }
}