# l10n.yaml
arb-dir: lib/l10n
template-arb-file: firebase_ui_auth_en.arb
output-localization-file: firebase_ui_auth_localizations.dart # Name of the generated file
output-class: FirebaseUiAuthLocalizations 